Models/Order.cs
extern alias DataAnnotations;
using System.Collections.Generic;
using System.ComponentModel;
using DataAnnotations.System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;

namespace LRI.MyPlace2Learn.Models
{
    [Bind(Exclude = "OrderId")]
    public partial class Order
    {

        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();

            LearningContext learningDB = new LearningContext();

            string status = (from dsv in learningDB.DatasetValues
                             where dsv.DatasetValueId == this.DSStatus
                             select dsv.Value).SingleOrDefault();

        }
           

           [ScaffoldColumn(false)]
            public int OrderId { get; set; }

            [ScaffoldColumn(false)]
            public int UserId { get; set; }

            [ScaffoldColumn(false)]
            public System.DateTime OrderDate { get; set; }


            [ScaffoldColumn(false)]
            public decimal Total { get; set; }

            [ScaffoldColumn(false)]
            public decimal VATRate { get; set; }
            
            public string Identifier { get; set; }

            [ScaffoldColumn(false)]
            public string Username { get; set; }

            [ScaffoldColumn(false)]
            [DefaultValue((int) 3)]
            public int DSStatus { get; set; }

            [DataAnnotations.System.ComponentModel.DataAnnotations.Schema.NotMapped]
            public string Status { get; set; }
            [DataAnnotations.System.ComponentModel.DataAnnotations.Schema.NotMapped]
            public string GrossTotal { get { return (Total + (Total * VATRate / 100)).ToString("0.00"); } }

            
            
            public virtual ICollection<OrderDetail> OrderDetails { get; set; }


        #region old

        //[ScaffoldColumn(false)]
        //public int OrderId { get; set; }

        //[ScaffoldColumn(false)]
        //public System.DateTime OrderDate { get; set; }

       

        //[Required(ErrorMessage = "First Name is required")]
        //[DisplayName("First Name")]
        //[StringLength(160)]
        //public string FirstName { get; set; }

        //[Required(ErrorMessage = "Last Name is required")]
        //[DisplayName("Last Name")]
        //[StringLength(160)]
        //public string LastName { get; set; }

        //[Required(ErrorMessage = "Address is required")]
        //[StringLength(70)]
        //public string Address { get; set; }

        //[Required(ErrorMessage = "City is required")]
        //[StringLength(40)]
        //public string City { get; set; }

        //[Required(ErrorMessage = "State is required")]
        //[StringLength(40)]
        //public string State { get; set; }

        //[Required(ErrorMessage = "Postal Code is required")]
        //[DisplayName("Postal Code")]
        //[StringLength(10)]
        //public string PostalCode { get; set; }

        //[Required(ErrorMessage = "Country is required")]
        //[StringLength(40)]
        //public string Country { get; set; }

        //[Required(ErrorMessage = "Phone is required")]
        //[StringLength(24)]
        //public string Phone { get; set; }

        //[Required(ErrorMessage = "Email Address is required")]
        //[DisplayName("Email Address")]
        //[RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}",
        //    ErrorMessage = "Email is is not valid.")]
        //[DataType(DataType.EmailAddress)]
        //public string Email { get; set; }

        //[ScaffoldColumn(false)]
        //public decimal Total { get; set; }

        //public List<OrderDetail> OrderDetails { get; set; }

        #endregion
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LRI.MyPlace2Learn.Models;
using LRI.MyPlace2Learn.Attributes;
using PagedList;
//using PagedList.Mvc;

namespace LRI.MyPlace2Learn.Controllers
{
    public class OrderController : Controller
    {
        private LearningContext db = new LearningContext();

        //
        // GET: /Order/5
        [Authorize]
        [LayoutSetter("_LayoutNoLeftMenu")]
        public ActionResult Index(int? id, int? page)
        {
            IQueryable<Order> orders;
            if (id > 0)
            {
                orders = db.Orders.Where(u=>u.UserId == id && u.DSStatus == 6);
            }
            else
            {
                int currentId = Convert.ToInt32(HttpContext.Session["UserId"]);
                orders = db.Orders.Where(u => u.UserId == currentId && u.DSStatus == 6);
            }
            return View(orders.OrderBy(o=>o.OrderDate).ToPagedList(page ?? 1, 10));
        }

        //
        // GET: /Order/Details/5
        [Authorize]
        [LayoutSetter("_LayoutNoLeftMenu")]
        public ActionResult Details(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // GET: /Order/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Order/Create

        [HttpPost]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        //
        // GET: /Order/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // POST: /Order/Edit/5

        [HttpPost]
        public ActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        //
        // GET: /Order/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // POST: /Order/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Order/Details.cshtml
@model LRI.MyPlace2Learn.Models.Order

@{
    ViewBag.Title = "Order Details";
}


<ul class="breadcrumb">
    <li><a href="@Url.Content("~/Home/")">Home</a> <span class="divider">/</span></li>
    <li><a href="@Url.Content("~/Order/")">Order History</a> <span class="divider">/</span></li>
    <li class="active">Order No. @Model.OrderId</li>
</ul>

<h2>Order No @Model.OrderId</h2>

<h4>Date @Model.OrderDate.ToShortDateString()</h4>
<br />
<div class= "span10">
<table class="table table-bordered table-striped">
<thead>
	<tr>
	    <th style = "width: 70%;">Title</th>
	    <th style = "width: 10%; text-align:center;">Price</th>	
	</tr>
</thead>
<tbody>

@foreach (var item in Model.OrderDetails)
{ 
    <tr>
        <td>@item.LearningResource.Title</td>
        <td style = "text-align:right;">£@item.UnitPrice.ToString("0.00")</td>
    </tr>

}</tbody>
<tfoot>
<tr style="height: 5px;"><td colspan = "2"></td></tr>
<tr>
        <td style = "text-align:right;">Total</td>
        <td style = "text-align:right;"><strong>£@Model.Total.ToString("0.00")</strong></td>
    </tr>
     <tr>
        <td style = "text-align:right;">VAT</td>
        <td style = "text-align:right;"><strong>£@(LRI.MyPlace2Learn.Utility.UtilityFunction.VATCalculation(Model.Total).ToString("0.00"))</strong></td>
    </tr>
     <tr>
        <td style = "text-align:right;">Order Total</td>
        <td style = "text-align:right;"><strong>£@((LRI.MyPlace2Learn.Utility.UtilityFunction.VATCalculation(Model.Total)+Model.Total).ToString("0.00"))</strong></td>
    </tr>
</tfoot>
</table>
</div>

Views/Order/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<LRI.MyPlace2Learn.Models.Order>

@{
    ViewBag.Title = "Order History";
}
<ul class="breadcrumb">
    <li><a href="@Url.Content("~/Home/")">Home</a> <span class="divider">/</span></li>
    <li class="active">@ViewBag.Title</li>
</ul>
<h2>@ViewBag.Title</h2><br />
<div class = "span10">
    <table class="table table-bordered table-striped">
    <thead>
	    <tr>
	        <th style = "width: 70%;">Order Date</th>
	        <th style = "width: 15%;">Order Number</th>
	        <th style = "width: 10%;">Total</th>
	        <th style = "width: 5%;"></th>			
	    </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        { 
            <tr>
                <td>@item.OrderDate.ToShortDateString()</td>
                <td>@item.OrderId</td>
                <td>£@item.GrossTotal</td>
                <td>@Html.ActionLink("View", "Details", "Order", new { id = item.OrderId }, new { @class = "btn btn-primary" })</td>
            </tr>
        }
    </tbody>
    </table>
</div>
<div class = "span10" style = "text-align:center;">
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>