Models/LearningCategory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
extern alias DataAnnotations;
using System;
using System.ComponentModel;
using DataAnnotations.System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Collections.Generic;


namespace LRI.MyPlace2Learn.Models
{   
  
    public class LearningCategory 
    {
        public LearningCategory()
        {
            this.LearningResources = new HashSet<LearningResource>();
        }
    
        public int LearningCategoryID { get; set; }
        [Required]
        [DisplayName("Category")]
        public string Name { get; set; }
        [Required]
        public string Reference { get; set; }
        public string Description { get; set; }
        public string ImageFileFolder { get; set; }
        public string ImageFileName { get; set; }
        public string ImageFileExt { get; set; }
        public Nullable<int> DSStatusID { get; set; }

        [DisplayName("Status*")]
        public bool IsActive { get; set; }
        
        public bool IsArchived { get; set; }
        
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> ParentLearningCategoryID { get; set; }
        public Nullable<System.Guid> LearningCategoryGUID { get; set; }
    
        public virtual ICollection<LearningResource> LearningResources { get; set; }
    }
    
}

Controllers/LearningCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LRI.MyPlace2Learn.Models;
using LRI.MyPlace2Learn.Attributes;
using PagedList;
//using PagedList.Mvc;

namespace LRI.MyPlace2Learn.Controllers
{
    [Authorize]
    [LayoutSetter("_LayoutNoLeftMenu")]
    public class LearningCategoryController : Controller
    {
        private LearningContext db = new LearningContext();

        //
        // GET: /LearningCategory/

        public ActionResult Index(int? page, int recordStatus = 1)
        {
            RecordStatusDisplay displayStatus = (RecordStatusDisplay)recordStatus;
            IQueryable<LearningCategory> query = db.LearningCategories;

            switch (displayStatus)
            { 
                case RecordStatusDisplay.Active:
                    query = query.Where(lc => lc.IsActive == true);
                    break;
                case RecordStatusDisplay.Inactive:
                    query = query.Where(lc => lc.IsActive == false);
                    break;
                case RecordStatusDisplay.All:
                    break;
            }

            return View(query.OrderBy(lc=>lc.Name).ToPagedList(page ?? 1, 10));
        }

        //
        // POST: /LearningCategory/
        [HttpPost]
        public ActionResult Index()
        {
            string status = Request.Form["status"];

            IQueryable<LearningCategory> learningCategories = db.LearningCategories
                                                              .OrderBy(c => c.Name);

            if (!string.IsNullOrEmpty(Request.Form["searchTerm"]))
            {
                learningCategories = learningCategories
                                     .Where(c => c.Name == Request.Form["searchTerm"]);
            }

            IPagedList<LearningCategory> filteredCategories = learningCategories.ToPagedList(1, 10);
            return View(filteredCategories);
        }
                
        //
        // GET: /LearningCategory/Details/5
        public ActionResult Details(int id = 0)
        {
            LearningCategory learningcategory = db.LearningCategories.Find(id);
            if (learningcategory == null)
            {
                return HttpNotFound();
            }
            return View(learningcategory);
        }
        
        //
        // POST: /LearningCategory/Create

        [HttpPost]
        public ActionResult Create(LearningCategory learningcategory)
        {
            if (ModelState.IsValid)
            {
                db.LearningCategories.Add(learningcategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(learningcategory);
        }

        //
        // GET: /LearningCategory/Edit/5

        public ActionResult Edit(int id = 0)
        {
            LearningCategory learningcategory = db.LearningCategories.Find(id);
            if (learningcategory == null)
            {
                return HttpNotFound();
            }
            return View(learningcategory);
        }

        //
        // POST: /LearningCategory/Edit/5
        [HttpPost]
        public ActionResult Edit(LearningCategory learningcategory)
        {
            if (ModelState.IsValid)
            {

                learningcategory.IsActive = (Request.Form["IsActive"] == "1");
                learningcategory.IsArchived = (Request.Form["IsActive"] == "0");
                learningcategory.LastUpdatedBy = Convert.ToInt32(Session["UserId"]);
                learningcategory.LastUpdatedOn = System.DateTime.Now;

                db.Entry(learningcategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(learningcategory);
        }

        //
        // GET: /LearningCategory/Archive/5
        public ActionResult Archive(int id, bool isArchive = true)
        {
            archive(db.LearningCategories.Find(id), isArchive);
            return RedirectToAction("Index");
        }

        private void archive(LearningCategory category, bool isArchive)
        { 
            category.IsActive = (isArchive) ? false : true;
            category.IsArchived = (isArchive) ? true : false;
            db.SaveChanges();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/LearningCategory/Edit.cshtml
@using LRI.MyPlace2Learn.Helpers
@model LRI.MyPlace2Learn.Models.LearningCategory

@{
    ViewBag.Title = "Administration: Learning Categories";
}

<ul class="breadcrumb">
	<li><a href="@Url.Content("~")">Home</a> <span class="divider">/</span></li>
    <li><a href="@Url.Content("~/LearningCategory/")">Admin: Learning Categories</a><span class="divider">/</span></li>
	 
        @if (Model == null)
        { 
           <li class="active">New Category</li>
        }
        else
        { 
           <li class="active">Edit Category</li>
        }
    
</ul>

    <h2>Learning Category Administration</h2>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{

    @Html.ValidationSummary(true, "Unable to create new learning category. Please correct the errors and try again.")
    @Html.HiddenFor(model=>model.LearningCategoryID)
    <div class = "span11">
            <fieldset>
                <legend>Category details</legend>
                <div class="span5 no_margin_left">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Name)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Reference)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Reference)
                        @Html.ValidationMessageFor(model => model.Reference)
                    </div>
                    <div class="control-group">
                   @Html.LabelFor(m => m.IsActive, new { @class = "control-label" })
                    <div class="controls docs-input-sizes">
                         @Html.DropDownList("IsActive", new SelectList(new StatusListItems((Model != null) ? Model.IsActive : true).ListItems, "Value", "Text"))                         
                    </div>
                </div>
                </div>
                <div class="span5 no_margin_left">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.Description, new { @class = "largeTextArea" })
                    </div>
                </div>
        </fieldset>
   </div>
   <div class="row span11">	
         <hr />  
        <input type="submit" value="Submit" class="btn btn-primary btn-large pull-right"/>
    </div>  
    
}

Views/LearningCategory/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<LRI.MyPlace2Learn.Models.LearningCategory>

@{
    ViewBag.Title = "Administration: Learning Categories";
}

<script src="../../Scripts/LRILibrary/jQuery.Utility.js" type="text/javascript"></script>
<ul class="breadcrumb">
	<li><a href="#">Home</a> <span class="divider">/</span></li>
    <li class="active">@ViewBag.Title</li>
</ul>
<h2>@ViewBag.Title</h2>

<br />
<div class = "span12 no_margin_left">
    <div>
     @using (Html.BeginForm("Index", "LearningCategory", FormMethod.Post, new { @class = "navbar-search" }))
     {
         <select name = "status" id = "status" class = "statusFilter">
            <option value = "1">Show Active</option>
            <option value = "0">Show Inactive</option>
            <option value = "2">Show All</option>
        </select>    
        <input type="text" class="span2" id = "searchTerm" name = "searchTerm" placeholder="Find category"/>
		<button class="btn btn-primary btn-small" style = "margin-bottom: 10px;" type="submit">Find</button>
        
      }   
   
    
     @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary pull-right" })
    </div>
</div>

<table class="table table-bordered table-striped">
<thead>
    <tr>
        <th>Category</th>    
        <th style="text-align:center;">Actions</th>
    </tr>
</thead>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td style="text-align: center;">
            @Html.ActionLink("Edit", "Edit", new { id = item.LearningCategoryID }) | 
            
            @if (item.IsActive)
            {
                @Html.ActionLink("Archive", "Archive", new { id = item.LearningCategoryID })
            }
            else
            { 
               @Html.ActionLink("Activate", "Activate", new { id = item.LearningCategoryID, isArchive = false }) 
            }

        </td>
    </tr>
}

</table>
<div class = "span12" style = "text-align:center;">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>